spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microbid
    username: microuser
    password: microsecret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

  application:
    name:
      task-bid

logging:
  level:
    org.example.taskbid.config.RestTemplateConfig: INFO
    org.apache.http: WARN


ml:
  service:
    url: http://localhost:8000

app:
  dev-seed:
    enabled: true
